import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/shared/ui/sonner";
import AppHeader from "@/widgets/header/ui/AppHeader";
import QueryProvider from "@/shared/providers/query-client-provider";
import { ErrorOverlayProvider } from '@/shared/components/ErrorOverlay';
import { ConditionalAuthGuard } from "@/shared/lib/conditional-auth-guard";
import { RealTimeProvider } from "@/shared/providers/RealTimeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-background text-foreground`}>
        <QueryProvider>
          <RealTimeProvider>
            <ErrorOverlayProvider>
              <ConditionalAuthGuard>
                <AppHeader />
                <Suspense fallback={null}>{children}</Suspense>
              </ConditionalAuthGuard>
              <Toaster />
            </ErrorOverlayProvider>
          </RealTimeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
